#!/bin/python
from sys import exit


a = raw_input().strip()
letter_list=["a","e","i","o","u","y"]
for i in range(0,len(a)-1):
    if a[i].lower!=a[i+1].lower:
        if any(a[i].lower==x for x in letter_list):
             if all(a[i+1].lower!=x for x in letter_list):
                    continue
    else:
        print("No")
        exit()
print("Yes")
    